apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deployment-prod
 namespace: bsj-dev
spec:
 selector:
   matchLabels:
    type: web
 replicas: 1
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: santhaim:react:latest
      envFrom:
      - configMapRef:
          name: httpd-cm-prod
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
